# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:

    # - task: NuGetCommand@2
    #   inputs:
    #     command: 'restore'
    #     restoreSolution: '**/*.sln'
    #     feedsToUse: 'select'
    #     vstsFeed: 'c4521e87-d5c9-442e-866e-c782ad69d302/f16ff7a7-765d-4fc8-9ad9-f53483e530a6'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Nuget Packages'
      inputs:
        command: 'restore'
        projects: '**/UserService/UserService.csproj'
        feedsToUse: 'select'
        vstsFeed: 'c4521e87-d5c9-442e-866e-c782ad69d302/f16ff7a7-765d-4fc8-9ad9-f53483e530a6'

    - task: SonarCloudPrepare@1
      displayName: Prepare SonarCloud
      inputs:
        SonarCloud: 'Kwetter SonarCloud'
        organization: '407383'
        scannerMode: 'MSBuild'
        projectKey: '407383_Kwetter'
        projectName: 'Kwetter'

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud'
    
    - task: DotNetCoreCLI@2
      displayName: Build UserService
      inputs:
        command: 'build'
        projects: '**/UserService/UserService.csproj'
    
    - task: SonarCloudPublish@1
      displayName: 'Publish results on build summary'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      inputs:
        containerRegistry: 'Kwetter'
        command: 'login'
        addPipelineData: false

    - task: Docker@2
      inputs:
        containerRegistry: 'Kwetter'
        repository: 'ramonaerts/kwetter-userservice'
        command: 'buildAndPush'
        Dockerfile: 'UserService/Dockerfile'
        tags: 'latest'
        addPipelineData: false
        
    - task: Docker@2
      inputs:
        containerRegistry: 'Kwetter'
        command: 'logout'
        addPipelineData: false
